#!/usr/bin/env bash
if [ $# -ne 1 ]; then
  echo "error: Give a number as a second argument"
  exit 1
fi
count=$1
tmux send-keys -t 1.1 $count C-m
for i in $(seq "$count"); do
  tmux send-keys -t 1.1 $i C-m
done
